version: '3.3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: <your_password>
      MYSQL_DATABASE: <your_database>
      MYSQL_USER: <your_username>
      MYSQL_PASSWORD: <your_password>
    ports:
      - "9999:3306"