version: '3.3'
services:
  db1:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "testlocality"
      MYSQL_USER: "pl"
      MYSQL_PASSWORD: "1234"
    ports:
      - "3307:3306"
  db2:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "testlocality"
      MYSQL_USER: "pl"
      MYSQL_PASSWORD: "1234"
    ports:
      - "3308:3306"
